io:
  getunleash:
    api-token: '*:development.19c3076363d5cd11099b5f5a22107d0b2d82dae82d8315e6a1391462'
    api-url: http://192.168.10.164:4242/api
    app-name: example-service
    environment: development
    instance-id: instance-2
    http-fetcher: ok_http
    custom-http-headers-provider:
      - name: X-APP
        value: dfsdfdsf
      - name: dfgdfg
        value: sdfsfgdfgdfg
    fetch-toggles-interval: 30s
